name: myapp
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  bilions_ui: ^1.0.19
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  cloud_firestore: ^4.7.0
  drop_down_list: ^0.0.4
  email_validator: ^2.1.17
  fancy_password_field: ^2.0.0
  file_picker: ^5.3.2
  firebase_auth: ^4.5.0
  firebase_core: ^2.14.0
  firebase_messaging: ^14.6.5
  firebase_storage: ^11.2.4
  flutter:
    sdk: flutter
  flutter_chat_ui: ^1.6.9
  flutter_chat_types: ^3.6.2
  flutter_dotenv: ^5.0.2
  flutter_firebase_chat_core: ^1.6.7
  flutter_redux: ^0.10.0
  freezed_annotation: ^2.4.1
  http: ^0.13.5
  image_picker: ^1.0.1
  json_annotation: ^4.8.1
  mime: ^1.0.4
  open_filex: ^4.3.2
  openfoodfacts: ^2.6.0
  path_provider: ^2.0.11
  persistent_bottom_nav_bar: ^5.0.2
  pretty_qr_code: ^2.0.2
  qr_code_scanner: ^1.0.1
  redux_epics: ^0.15.1 
  redux: ^5.0.0 
  rxdart: ^0.27.7
  settings_ui: ^2.0.2

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  freezed: ^2.4.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/icons8-google-96.png
    - assets/icons/icons8-qr-code-48.png
    - assets/icons/icons8-star-filled-50.png
    - assets/icons/icons8-favorite-50.png
    - assets/icons/icons8-account-50.png
    - assets/icons/icons8-statistics-report-50.png
    - assets/icons/icons8-notification-center-50.png
    - assets/icons/icons8-chat-message-50.png
    - assets/icons/icons8-info-squared-50.png
    - assets/icons/icons8-share-50.png
    - assets/icons/icons8-feedback-50.png
    - assets/icons/icons8-question-mark-50.png
    - assets/icons/icons8-camera-64.png
    - assets/icons/icons8-ingredients-50.png
    - assets/icons/icons8-instructions-49.png
    - assets/icons/icons8-video-64.png
    - .env