// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      // ignore: no_default_cases
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoWLHPNqNp3c8Epar5xz3p_OOWStobPMc',
    appId: '1:885014642180:android:db31ee98ad62bc9914ff51',
    messagingSenderId: '885014642180',
    projectId: 'foodie-traker-v2',
    storageBucket: 'foodie-traker-v2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYSDrmz5Z1ReOEMr29BIz4rCY7u_doBts',
    appId: '1:885014642180:ios:26660a30887b381e14ff51',
    messagingSenderId: '885014642180',
    projectId: 'foodie-traker-v2',
    storageBucket: 'foodie-traker-v2.appspot.com',
    androidClientId: '885014642180-09np0f1boadllmqv3p89jj6ph5aq46o3.apps.googleusercontent.com',
    iosClientId: '885014642180-0bqu3mou4qucngn8etq7drhb6u5b6dqm.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );
}
