part of '../index.dart';

@freezed
class Recipe with _$Recipe {
  factory Recipe({
    @JsonKey(name: 'idMeal') required String id,
    @JsonKey(name: 'strMeal') required String name,
    @JsonKey(name: 'strDrinkAlternate') String? matchingDrink,
    @JsonKey(name: 'strCategory') required String category,
    @JsonKey(name: 'strArea') String? area,
    @JsonKey(name: 'strInstructions') required String instructions,
    @JsonKey(name: 'strMealThumb') required String pictureUrl,
    @JsonKey(name: 'strTags') String? tags,
    @JsonKey(name: 'strYoutube') String? videoUrl,
    @JsonKey(name: 'strIngredient1') required String? ingredient1,
    @JsonKey(name: 'strIngredient2') required String? ingredient2,
    @JsonKey(name: 'strIngredient3') required String? ingredient3,
    @JsonKey(name: 'strIngredient4') required String? ingredient4,
    @JsonKey(name: 'strIngredient5') required String? ingredient5,
    @JsonKey(name: 'strIngredient6') required String? ingredient6,
    @JsonKey(name: 'strIngredient7') required String? ingredient7,
    @JsonKey(name: 'strIngredient8') required String? ingredient8,
    @JsonKey(name: 'strIngredient9') required String? ingredient9,
    @JsonKey(name: 'strIngredient10') required String? ingredient10,
    @JsonKey(name: 'strIngredient11') required String? ingredient11,
    @JsonKey(name: 'strIngredient12') required String? ingredient12,
    @JsonKey(name: 'strIngredient13') required String? ingredient13,
    @JsonKey(name: 'strIngredient14') required String? ingredient14,
    @JsonKey(name: 'strIngredient15') required String? ingredient15,
    @JsonKey(name: 'strIngredient16') required String? ingredient16,
    @JsonKey(name: 'strIngredient17') required String? ingredient17,
    @JsonKey(name: 'strIngredient18') required String? ingredient18,
    @JsonKey(name: 'strIngredient19') required String? ingredient19,
    @JsonKey(name: 'strIngredient20') required String? ingredient20,
    @JsonKey(name: 'strMeasure1') required String? measure1,
    @JsonKey(name: 'strMeasure2') required String? measure2,
    @JsonKey(name: 'strMeasure3') required String? measure3,
    @JsonKey(name: 'strMeasure4') required String? measure4,
    @JsonKey(name: 'strMeasure5') required String? measure5,
    @JsonKey(name: 'strMeasure6') required String? measure6,
    @JsonKey(name: 'strMeasure7') required String? measure7,
    @JsonKey(name: 'strMeasure8') required String? measure8,
    @JsonKey(name: 'strMeasure9') required String? measure9,
    @JsonKey(name: 'strMeasure10') required String? measure10,
    @JsonKey(name: 'strMeasure11') required String? measure11,
    @JsonKey(name: 'strMeasure12') required String? measure12,
    @JsonKey(name: 'strMeasure13') required String? measure13,
    @JsonKey(name: 'strMeasure14') required String? measure14,
    @JsonKey(name: 'strMeasure15') required String? measure15,
    @JsonKey(name: 'strMeasure16') required String? measure16,
    @JsonKey(name: 'strMeasure17') required String? measure17,
    @JsonKey(name: 'strMeasure18') required String? measure18,
    @JsonKey(name: 'strMeasure19') required String? measure19,
    @JsonKey(name: 'strMeasure20') required String? measure20,
    @JsonKey(name: 'strSource') String? source,
    @JsonKey(name: 'strImageSource') String? imageSource,
    @JsonKey(name: 'strCreativeCommonsConfirmed') String? cretiveCommonsConfirmed,
    @JsonKey(name: 'dateModified') String? dateModified,
  }) = _Recipe;

  factory Recipe.fromJson(Map<String, dynamic> json) => _$RecipeFromJson(json);
}
